baseURL = 'https://best-lirik-lagu.vercel.app'
languageCode = 'id'
title = 'Best Lirik Lagu'
theme = "blowfish"

[permalinks]
  post = '/:slug/'

[related]
  includeNewer = false
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'categories'
  weight = 100
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
[params]
  showRelated = true
  relatedLimit = 3

[params.homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 5
  showRecentHeader = true

[params.homepage]
  layout = "page"
  showFeatured = true
  featuredLimit = 5 
  showFeaturedHeader = true

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menu.main]]
  name = "Semua Lirik"
  pageRef = "/post/"
  weight = 20

[[menu.main]]
  name = "Kategori"
  pageRef = "/categories/"
  weight = 30
