baseURL = 'https://vercel.app'
languageCode = 'id'
title = 'Best Lirik Lagu'
theme = "blowfish"

[permalinks]
  post = '/:slug/'

# 1. LOGIKA UTAMA RELATED POSTS (MEKSA HUGO MUNG MACA CATEGORIES)
[related]
  includeNewer = true
  threshold = 10              # threshold didhunke pol ben gampang nyangkut
  toLower = true
[[related.indices]]
  name = 'categories'         # Murni mung nggoleki kecocokan kategori (minang / sunda)
  weight = 100
[[related.indices]]
  name = 'date'               # Yen kategorine padha, diurutne adhedhasar tanggal sing cedhak
  weight = 10

[params]
  # Fitur bawaan Blowfish

[params.article]
  showRelated = true          # Ngaktifake terkait neng ngisor artikel
  relatedLimit = 3

# 2. LOGIKA UTAMA HOMEPAGE (LAYOUT CARD CEKATAN + RECENT POSTS RAME)
[params.homepage]
  layout = "card"             # Tampilan kartu kothak-kothak modern cocok nggo lirik
  showRecent = true
  recentLimit = 12            # Langsung keki 12 list artikel neng ngarep ben ketok rame lan kebak
  showRecentHeader = true
  cardView = true

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menu.main]]
  name = "Semua Lirik"
  pageRef = "/post/"
  weight = 20

[[menu.main]]
  name = "Kategori"
  pageRef = "/categories/"
  weight = 30
