<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>XML Sitemap - Best Lirik Lagu</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style>
*{box-sizing:border-box}
body{font-family:sans-serif;font-size:14px;color:#333;margin:0;background-color:#f0f2f5}
header{background: linear-gradient(135deg, #022448, #034f84);padding:15px;color:#ffffff;text-align:center;width:100%;margin-bottom:15px}
header h1{font-size:24px;margin: 0}
.siteseo-sitemap-container{position:relative;padding:15px;max-width:1000px;margin:0 auto 10px auto}
.siteseo-sitemap-container a{color:#007bff;text-decoration:none}
.siteseo-sitemap-table-wrap{background-color:#ffffff;box-shadow:0 2px 4px rgba(0, 0, 0, 0.1);border-radius:8px;margin-top:10px;overflow:auto}
table{width:100%;border-collapse:collapse}
th{background:#034f84;color:#fff;text-align:left;padding:12px}
td{padding:12px;border-bottom:1px solid #ddd;word-break:break-all;white-space:normal;font-size:11px}
tbody tr:nth-child(even) {background-color:rgb(240, 249, 255)}
tr:hover{background:#f5f5f5}
a{color:#428bca;text-decoration:none}
a:hover{text-decoration:underline}
</style>
</head>
<body>
<header>
  <h1>XML Sitemap - Best Lirik Lagu</h1>
  <span>Generated by Lorok™</span>
  <div class="siteseo-description">This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs</div>
</header>
<div class="siteseo-sitemap-container">
<div class="siteseo-sitemap-table-wrap">
        <table>
          <thead>
            <tr>
              <th>URL / Alamat Halaman</th>
              <th>Update Terakhir</th>
              <th>Frekuensi</th>
              <th>Prioritas</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td>
                  <xsl:variable name="itemURL" select="sitemap:loc"/>
                  <a href="{$itemURL}" target="_blank" rel="noopener"><xsl:value-of select="sitemap:loc"/></a>
                </td>
                <td><xsl:value-of select="substring(sitemap:lastmod,1,10)"/></td>
                <td><xsl:value-of select="sitemap:changefreq"/></td>
                <td><xsl:value-of select="sitemap:priority"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
</div>
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
