<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html lang="id">
<head>
<title>Google News XML Sitemap - Best Lirik Lagu</title> 
<style>
body{font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;color:#333;margin:0;padding:0;background:#f9f9f9}
#content{position:relative;padding:15px;max-width:1000px;margin:0 auto}
h1{color:#1a73e8;font-size:24px;margin:0 0 15px 0}
p{color:#666;font-size:14px;margin-top:0;margin:15px auto}
table{width:100%;border-collapse:collapse;background: #fff;box-shadow:0 1px 3px rgba(0,0,0,0.1);border-radius:4px;overflow:hidden;margin:15px auto}
th{background:#1a73e8;color:#fff;text-align:left;padding:12px;font-size:14px;font-weight:600}
td{padding:8px 12px;border-bottom:1px solid #eee;word-break:break-all;white-space:normal;font-size:11px;line-height:1.2}
tr:hover td{background:#f5f8ff}
a{color:#1a73e8;text-decoration:none;font-weight:500}
a:hover{text-decoration:underline}
.date{color:#777;font-size:13px}
</style>
</head>
<body>
<div id="content">
<h1>Google News XML Sitemap - Best Lirik Lagu</h1>
<span>Generated by Lorok™</span>
<p>Artikel terbaru.</p>
            <table id="sitemap">
                <thead>
                        <tr>
                            <th>Judul Berita</th>
                            <th>Nama Publikasi</th>
                            <th>Bahasa</th>
                            <th>Tanggal Terbit</th>
                        </tr>
                </thead>
                <tbody>
                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                            <tr>
                                <td><a href="{sitemap:loc}" target="_blank" rel="noopener"><xsl:value-of select="news:news/news:title"/></a></td>
                                <td><xsl:value-of select="news:news/news:publication/news:name"/></td>
                                <td><xsl:value-of select="news:news/news:publication/news:language"/></td>
                                <td class="date"><xsl:value-of select="news:news/news:publication_date"/></td>
                            </tr>
                    </xsl:for-each>
                </tbody>
            </table>
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>