<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html>
<head>
<title>RSS Sitemap - Best Lirik Lagu</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<style>
body{font-family:sans-serif;font-size:14px;color:#333;margin:0;background-color:#f0f2f5}
#content{position:relative;padding:15px;max-width:1000px;margin:0 auto}
h1{color:#034f84;margin:0 auto 15px auto;font-size:24px}
table{width:100%;border-collapse:collapse;margin:15px auto;background:#fff;box-shadow: 0 1px 3px rgba(0,0,0,0.1)}
th{background:#034f84;color:#fff;text-align:left;padding:12px}
td{padding:8px 12px;border-bottom:1px solid #ddd;word-break:break-all;white-space:normal;font-size:11px}
tbody tr:nth-child(even) {background-color:rgb(240, 249, 255)}
tr:hover{background:#f5f5f5}
a{color:#007bff;text-decoration:none}
a:hover{text-decoration:underline}
.expl{margin:18px auto;line-height:1.2em;font-size:14px;color:#555}
.expl a,.expl strong{color:#da3114;font-weight:600}
</style>
</head>
<body>
<div id="content">
<h1>RSS Sitemap - Best Lirik Lagu</h1>
<p class="expl">Generated by <strong>Lorok™</strong>, this is an RSS Sitemap, meant for consumption by search engines.<br/>
You can find more information about RSS sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener">sitemaps.org</a>.</p>
<p class="expl">This RSS Sitemap file contains <xsl:value-of select="count(//*[local-name()='item'])"/> URLs.</p>
            <table id="sitemap">
                <thead>
                    <tr>
                        <th width="50%">Judul Lirik / Halaman</th>
                        <th width="30%">Link URL</th>
                        <th width="20%">Tanggal Rilis (PubDate)</th>
                    </tr>
                </thead>
                <tbody>
                    <xsl:for-each select="//*[local-name()='item']">
                    <tr>
                        <td><xsl:value-of select="*[local-name()='title']"/></td>
                        <td>
                            <xsl:variable name="itemURL">
                                <xsl:value-of select="*[local-name()='link']"/>
                            </xsl:variable>
                            <a href="{$itemURL}" target="_blank" rel="noopener">
                                <xsl:value-of select="*[local-name()='link']"/>
                            </a>
                        </td>
                        <td><xsl:value-of select="*[local-name()='pubDate']"/></td>
                    </tr>
                    </xsl:for-each>
                </tbody>
            </table>
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
